name = "deepthought_lean_eval"
version = "0.1.0"
defaultTargets = ["deepthought_lean_eval"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "32d24245c7a12ded17325299fd41d412022cd3fe"

[[lean_lib]]
name = "DeepthoughtLeanEval"

[[lean_exe]]
name = "deepthought_lean_eval"
root = "Main"
